-- MySQL Script generated by MySQL Workbench
-- Thu May  7 09:31:46 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema banco
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `banco` ;
USE `banco` ;

-- -----------------------------------------------------
-- Table `banco`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `numero` CHAR(14) NOT NULL,
  `matricula` CHAR(16) NOT NULL,
  `admin` INT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`categoria` (
  `idcategoria` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`anuncio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`anuncio` (
  `idanuncio` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `descricao` TEXT(1000) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  `periodoaluguel` VARCHAR(45) NULL,
  `troca` VARCHAR(45) NOT NULL,
  `idcategoria` INT NOT NULL,
  `status` VARCHAR(255) NOT NULL,
  `idusuario` INT NOT NULL,
  `datahora` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idanuncio`),
  INDEX `fk_anuncio_categoria_idx` (`idcategoria` ASC) VISIBLE,
  INDEX `fk_anuncio_usuarios1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_anuncio_categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `banco`.`categoria` (`idcategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_anuncio_usuarios1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `banco`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`imagem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`imagem` (
  `idimagem` INT NOT NULL AUTO_INCREMENT,
  `idanuncio` INT NOT NULL,
  `caminho` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idimagem`),
  INDEX `fk_imagem_anuncio1_idx` (`idanuncio` ASC) VISIBLE,
  CONSTRAINT `fk_imagem_anuncio1`
    FOREIGN KEY (`idanuncio`)
    REFERENCES `banco`.`anuncio` (`idanuncio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `banco`.`favorito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`favorito` (
  `idusuario` INT NOT NULL,
  `idanuncio` INT NOT NULL,
  PRIMARY KEY (`idusuario`, `idanuncio`),
  INDEX `fk_usuarios_has_anuncio_anuncio1_idx` (`idanuncio` ASC) VISIBLE,
  INDEX `fk_usuarios_has_anuncio_usuarios1_idx` (`idusuario` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_has_anuncio_usuarios1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `banco`.`usuarios` (`idusuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuarios_has_anuncio_anuncio1`
    FOREIGN KEY (`idanuncio`)
    REFERENCES `banco`.`anuncio` (`idanuncio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `banco` ;

-- -----------------------------------------------------
-- Placeholder table for view `banco`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `banco`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `banco`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `banco`.`view1`;
USE `banco`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
