version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_lab
    restart: always
    # O comando abaixo força o MySQL a iniciar com o fuso de Brasília
    command: --default-time-zone='-03:00' 
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: banco
      TZ: America/Sao_Paulo # Ajusta o relógio do sistema operacional do container
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./banco:/docker-entrypoint-initdb.d

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_apache_lab
    restart: always
    environment:
      TZ: America/Sao_Paulo # É bom deixar o PHP no mesmo fuso do banco
    ports:
      - "81:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
      - db

volumes:
  db_data: